name: simplenote_to_obsidian
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  path: ^1.8.1
  diacritic: ^0.1.3
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
